"""Verified deterministic products for cheap PDB/mmCIF perturbations (#812/#822)."""
from __future__ import annotations

import hashlib
import json
import re
import sys
import tempfile
from pathlib import Path
from typing import Mapping

from refinement_cache import CacheEvidenceError


def generator_identity(producer: str, algorithm: str, **dependencies) -> dict:
    """Conservatively bind the producing script, runtime and named dependencies."""
    return {
        "algorithm": algorithm,
        "producer_sha256": hashlib.sha256(Path(producer).read_bytes()).hexdigest(),
        "python_implementation": sys.implementation.name,
        "python_version": sys.version,
        **dependencies,
    }


def _verified(destination: Path, filename: str, evidence: bytes, expected: bytes) -> Path:
    """Do not repair or adopt missing, corrupted, or legacy cache products."""
    bundle = destination / "bundle"
    product = bundle / filename
    manifest = bundle / "evidence.json"
    if (destination.is_symlink() or not destination.is_dir()
            or bundle.is_symlink() or not bundle.is_dir()
            or product.is_symlink() or manifest.is_symlink()):
        raise CacheEvidenceError(f"Invalid deterministic cache: {destination}")
    try:
        valid = manifest.read_bytes() == evidence and product.read_bytes() == expected
    except OSError as error:
        raise CacheEvidenceError(f"Incomplete deterministic cache: {destination}") from error
    if not valid:
        raise CacheEvidenceError(f"Changed deterministic evidence: {destination}")
    return product


def deterministic_product(
    work: Path, operation: str, *, filename: str, provenance: Mapping, expected: bytes,
) -> Path:
    """Store/reuse only the exact regenerated bytes and invocation evidence.

    The caller must compute expected bytes from the declared source/parameters.
    Regeneration is cheap and authenticates the actual result independently of
    the generator's name. New identities get separate bundles; old evidence is
    never overwritten. Even an incomplete reserved destination fails closed.
    """
    for label in (operation, filename):
        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]*", label):
            raise ValueError("Operation and product names must be simple filenames")
    if filename == "evidence.json" or {"contract", "operation", "output"} & provenance.keys():
        raise ValueError("Reserved deterministic-evidence name")
    record = {
        "contract": 1, "operation": operation, **provenance,
        "output": {"path": filename, "sha256": hashlib.sha256(expected).hexdigest()},
    }
    evidence = (json.dumps(record, sort_keys=True, indent=2, allow_nan=False) + "\n").encode()
    key = hashlib.sha256(evidence).hexdigest()
    family = work.resolve() / "deterministic_cache_v1" / operation
    destination = family / key
    if destination.exists() or destination.is_symlink():
        return _verified(destination, filename, evidence, expected)

    family.mkdir(parents=True, exist_ok=True)
    attempt = Path(tempfile.mkdtemp(prefix=f".attempt-{key[:16]}-", dir=family))
    (attempt / filename).write_bytes(expected)
    (attempt / "evidence.json").write_bytes(evidence)
    # Reserve rather than overwrite even an incomplete historical destination.
    try:
        destination.mkdir()
    except FileExistsError:
        return _verified(destination, filename, evidence, expected)
    attempt.rename(destination / "bundle")
    return _verified(destination, filename, evidence, expected)
